### ISSUE TITLE
What parser is well fit for handbars-18next

### ISSUE THREAD

**Issue by imike57** [UUDigitalHumanitieslab/handlebars-i18next#7]
Thank's for this helper ! 

I have some difficult to find a parser really fit to work with. 
For example currently I'm using https://github.com/i18next/i18next-parser, but it not allow to work with the nice features of handlebars-i18next like block helpers and interpolate. 

Do you know a parser which work perfectly with handbars-18next ?

**Comment by jgonggrijp** [comment]
Thanks for the good question @imike57! I have not tried using one of the existing parsers yet, so please take my answer with a grain of salt. I will however be trying to parse Handlebars templates for i18next strings in the near future, so maybe we can help each other out.

Besides i18next-parser, the [extraction tools](https://www.i18next.com/overview/plugins-and-utils#extraction-tools) section in the i18next documentation also mentions [i18next-scanner](http://i18next.github.io/i18next-scanner). That one doesn't ship with any Handlebars parser by itself, but there is a [recipe](https://github.com/i18next/i18next-scanner/wiki/Integration-Guide#handlebars) for Handlebars in its documentation. Note that that section starts with explaining how you can roll your own i18next helper for Handlebars, which you don't need if you are already using handlebars-i18next. The final example however demonstrates a parser for i18next-scanner that does seem to support block helpers. That example assumes the syntax from their example Handlebars helper, which seems to be slightly different from handlebars-i18next, so it might require some adapting to get correct results.

Alternatively, you might try improving on the Handlebars lexer that ships with i18next-parser. In either case, it doesn't seem like there is a completely ready-to-use solution, unfortunately. Maybe there is a "hidden gem" somewhere that does a better job out of the box, but my quick search didn't turn up anything.

If you find (or create) a good solution, please let me know! I'll do the same.

**Comment by jgonggrijp** [comment]
Currently working on this in https://github.com/UUDigitalHumanitieslab/handlebars-i18next-parser. Relevant: https://github.com/i18next/i18next-parser/issues/532.

**Comment by jgonggrijp** [comment]
@imike57 I just released a package which does the job: https://www.npmjs.com/package/handlebars-i18next-parser. Please try it out and feel welcome to submit feedback to https://github.com/UUDigitalHumanitieslab/handlebars-i18next-parser/issues.

I'll update handlebars-i18next soon so the README refers to the sister package. I'm going to close this ticket now, as there is an official solution, but discussion is still welcome.
